### ISSUE TITLE
Problem when executing Bard().get_answer(...)

### ISSUE THREAD

**Issue by vipin211** [dsdanielpark/Bard-API#1] opened 2023-05-14 20:47 UTC
Bard-API/bardapi/core.py", line 32, in _get_snim0e
    return re.search(r"SNlM0e\":\"(.*?)\"", resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dsdanielpark** [comment] 2023-05-14 21:55
**Occurs when response is not possible.**

1. First, check if the Google Bard is officially in service. You need to access **'https://bard.google.com/'** with your account and check if the result for the prompt is returned normally. If it is not an officially **serviced area**, the package will not work.
2. Second, check if you copied the value of `__Secure-1PSID` correctly. Also, restart your browser and try again. It may be a non-response error due to an invalid cookie.
3. In the case of **Google Colab**, I confirmed that it does not work even if I enter the correct `__Secure-1PSID`. Try again with different environment settings. Check if it works fine for other colleagues in the s**ame country or region.**

If the same error is repeated even after checking all of the above, please tell me **your Python environment, country, and region.**

**Comment by dsdanielpark** [comment] 2023-05-14 22:23
I checked the error in advance and considered exception handling, but because it was impossible to respond for various reasons, I did not handle it to explain if the good issue you suggested was created. Thanks again for creating a good issue.

**Comment by srulik-ben-david** [comment] 2023-05-15 07:04
It also didn't work out for me.
run locally on mac os, python 3.9, and got the following error:

`{'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n54\\n[["di",82],["af.httprm",82,"5948628323670192505",4]]\\n25\\n[["e",4,null,null,129]]\\n\'.'}
`

**Comment by dsdanielpark** [comment] 2023-05-15 10:58
> It also didn't work out for me. run locally on mac os, python 3.9, and got the following error:
> 
> `{'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n54\\n[["di",82],["af.httprm",82,"5948628323670192505",4]]\\n25\\n[["e",4,null,null,129]]\\n\'.'} `

In the case of Response Error: , it is returned when the key value is correct but the status value is not normal. (Occurs when status is not 200.)

1. Visit https://bard.google.com/ and check if you are in the right state to talk to the bard. 
    - Bard's current official service area can be viewed at: https://support.google.com/bard/answer/13575153?hl=en

**Comment by nu110** [comment] 2023-05-15 11:43
I get the same error when running latest version from Git under Python 3.10.6 on Ubuntu

`{'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n55\\n[["di",99],["af.httprm",99,"8116501196847996776",10]]\\n25\\n[["e",4,null,null,130]]\\n\'.'}`

**Comment by josanabr** [comment] 2023-05-15 19:27
I'm using a modified version of the jupyter-all-spark docker container and it does not work too,

```python
from bardapi import Bard
import os

os.environ['_BARD_API_KEY'] = __Secure_1PSID
Bard().get_answer('How many people are living in USA?')['content']
``` 

Response:

```
'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n57\\n[["di",139],["af.httprm",139,"7181192826173164579",13]]\\n25\\n[["e",4,null,null,132]]\\n\'.'
```

**Comment by DLesmes** [comment] 2023-05-15 22:35
I got the same error message 🔥 

`Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",152],["af.httprm",152,"-803832082914807468",2]]\n25\n[["e",4,null,null,131]]\n'.
`

run into a [deepnote notebook](https://deepnote.com/workspace/huntyjobs-79f2197f-649e-4006-a1a7-6a3dbbb620d0/project/bard-ecbf1122-5546-4447-80d0-e24d08c0a0fa/notebook/bardapi-f6887d051df24fdb87c4b233e95a68a3) with python 3.9 it is a linux console 🤔

**Comment by dsdanielpark** [comment] 2023-05-16 04:13
Currently, it is impossible to use behind a proxy. (Google Colab, container, virtual environment, internal network, etc.) 
If there are other solutions, don't hesitate to submit a pull request.

#5 - related issue.

**Comment by dsdanielpark** [comment] 2023-05-16 07:46
https://github.com/dsdanielpark/Bard-API/issues/1#issuecomment-1548705886, https://github.com/dsdanielpark/Bard-API/issues/1#issuecomment-1548449059, https://github.com/dsdanielpark/Bard-API/issues/1#issuecomment-1547699318, https://github.com/dsdanielpark/Bard-API/issues/1#issuecomment-1547298222

It is an error caused by server delay, and it is resolved by updating the timeout factor. This issue was resolved with #6 merge. This has been resolved since bardapi 0.1.3.

```
from bardapi import Bard
import os

os.environ['_BARD_API_KEY']="xxxxxxxxxxxx."
# Change 'http://127.0.0.1:1080' to your http proxy
# timeout in seconds
Bard(timeout=10).get_answer("나와 내 동년배들이 좋아하는 뉴진스에 대해서 알려줘")['content']
```

**Comment by dsdanielpark** [comment] 2023-05-16 15:55
This is an error related to Google's internal authentication, so you should
be able to talk to bard normally on the following site. If you can talk,
try refreshing the cookies and trying again. Also, the bard service is
currently available in limited areas only.

Please check this link.
https://stackoverflow.com/questions/16230850/httpsconnectionpool-max-retries-exceeded



2023년 5월 17일 (수) 오전 12:01, chercavs ***@***.***>님이 작성:

**Comment by seaberry0620** [comment] 2023-05-17 05:13
It worked for me when I cleared my cookies and logged back in to Bard.

**Comment by zkhalido** [comment] 2023-05-17 20:09
I was getting the same error. All I had to do was add `bard_inproxy = Bard(timeout=10)`

Something interesting I noticed, if I keep the original Korean text in the prompt I did not get the error... 
but replacing the original prompt with strictly English text gave me the error.

```python
from bardapi import Bard
import os

os.environ['_BARD_API_KEY']='your __Secure-1PSID value'
bard_inproxy = Bard(timeout=10)

response = Bard().get_answer("meanining of life")['content']

print(response)
```

**Comment by dsdanielpark** [comment] 2023-05-17 20:17
> I was getting the same error. All I had to do was add `bard_inproxy = Bard(timeout=10)`
> 
> Something interesting I noticed, if I keep the original Korean text in the prompt I did not get the error... but replacing the original prompt with strictly English text gave me the error.
> 
> ```python
> from bardapi import Bard
> import os
> 
> os.environ['_BARD_API_KEY']='your __Secure-1PSID value'
> bard_inproxy = Bard(timeout=10)
> 
> response = Bard().get_answer("meanining of life")['content']
> 
> print(response)
> ```


Use this code.
```
from bardapi import Bard
import os

os.environ['_BARD_API_KEY']='your __Secure-1PSID value'
bard = Bard(timeout=10)

response = bard .get_answer("meanining of life")['content']

print(response)
```

**Comment by jay67nie** [comment] 2023-05-17 22:22
I get a 'No module named "requests" ' error from the importation of Bard.

**Comment by zkhalido** [comment] 2023-05-17 22:26
You may not have it installed. Requests gets called in core, but it is not
part of bardapi.

https://pypi.org/project/requests/

**Comment by dsdanielpark** [comment] 2023-05-18 03:01
> I get a 'No module named "requests" ' error from the importation of Bard.

```
pip install requests
```

It is included in the development version, but not included in the pypi version, so it has been included since version 0.1.5. thank you

**Comment by vuthehuy1997** [comment] 2023-05-18 03:42
> Bard-API/bardapi/core.py", line 32, in _get_snim0e return re.search(r"SNlM0e":"(.*?)"", resp.text).group(1) AttributeError: 'NoneType' object has no attribute 'group'

You need to press Try Bard on bard.google.com

**Comment by NightMachinery** [comment] 2023-05-18 15:27
Which countries does Bard support?

**Comment by dsdanielpark** [comment] 2023-05-18 15:57
> Which countries does Bard support?

Bard's current official service area can be viewed at: https://support.google.com/bard/answer/13575153?hl=en

**Comment by dsdanielpark** [comment] 2023-05-23 14:14
[usr-canis](https://github.com/usr-canis)

Please uninstall the previous version of Googletrans as it is not included in the current Bard API. Install the latest version again, please.
```
pip install git+https://github.com/dsdanielpark/Bard-API.git
```

**Comment by GordonLevy** [comment] 2023-05-23 22:41
can the latest version - `git+https://github.com/dsdanielpark/Bard-API.git`
be exported to requirements.txt file and then installed with command -  `install via pip install -r requirements.txt` ?

**Comment by dsdanielpark** [comment] 2023-05-24 04:44
> can the latest version - `git+https://github.com/dsdanielpark/Bard-API.git` be exported to requirements.txt file and then installed with command - `pip install -r requirements.txt` ?

If you want to use Korean, English, and Japanese as mentioned in the README, you can simply use pip install bard. 

However, if you want to receive translated responses from Google Translate in various languages by passing the language parameter, you can install it using `git+https://github.com/dsdanielpark/Bard-API.git`. You don't need to install any separate requirements.

However, using the GitHub version may result in slower performance because it involves two requests during the translation process.

**Comment by zapqqqwe** [comment] 2023-05-24 08:24
Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n54\n[["di",75],["af.httprm",75,"6198447553110271097",8]]\n25\n[["e",4,null,null,129]]\n'.
[]
i use the code. bard = Bard(token=token,proxies={'http':'http://127.0.0.1:7890', 'https':'http://127.0.0.1:7890'}, timeout=10)
however i still meet the error,what should i do?

**Comment by chavarera** [comment] 2023-05-24 13:37
@dsdanielpark  

Is there any known frequency of receiving "response errors" after 30-40 requests? I have also attempted to reset the cookies, but unfortunately, I have not any success so far.

I tried

1. reset cookies

**Comment by zapqqqwe** [comment] 2023-05-25 02:14
i know .thank you.
&nbsp;


...
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 晚上10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dsdanielpark/Bard-API] Problem when executing Bard().get_answer(...) (Issue #1)





 
chavarera
 
In any case, this Python package is not an official Bard API. In addition, since the cookie value is eventually bound and recorded in your Google account, sending a large number of requests may limit the use of the service.

**Comment by ameywtf** [comment] 2023-06-03 19:56
This error still occurs for me.

```
{'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n54\\n[["di",65],["af.httprm",64,"5086034706703496976",9]]\\n25\\n[["e",4,null,null,129]]\\n\'.'}
```

I am using the github developer version (`pip install git+https://github.com/dsdanielpark/Bard-API.git`), I tried using the other (`pip install bardapi` version too by uninstalling this one and using that but i still get the error

I tried AsyncBard and Bard both

**Comment by zapqqqwe** [comment] 2023-06-04 02:44
have no idea.google limit the times to use .


...
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dsdanielpark/Bard-API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月4日(星期天) 凌晨3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dsdanielpark/Bard-API] Problem when executing Bard().get_answer(...) (Issue #1)





 
This error still occurs for me.
 {'content': 'Response Error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n54\\n[["di",65],["af.httprm",64,"5086034706703496976",9]]\\n25\\n[["e",4,null,null,129]]\\n\'.'}  
I am using the github developer version (pip install git+https://github.com/dsdanielpark/Bard-API.git), I tried using the other (pip install bardapi version too by uninstalling this one and using that but i still get the error
 
I tried AsyncBard and Bard both

**Comment by lapnd** [comment] 2023-06-10 10:06
In my case, I have logged in multiple google account, the token does not work. After using Incognito mode and login with single google account only, the token on this mode work fine

**Comment by Saugatkafley** [comment] 2023-06-11 15:08
I am also facing issue when I am hosting the app in streamlit. But it works completely fine on localhost. 

While i host in streamlit , i got 

`
Response Error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n57\n[["di",239],["af.httprm",239,"-7873719745301190719",0]]\n25\n[["e",4,null,null,132]]\n'.
`

**Comment by Saugatkafley** [comment] 2023-06-11 15:09
Any fixes?

**Comment by thispath98** [comment] 2023-06-12 06:47
@Saugatkafley 

Same error occurs for me. I am deploying app with Streamlit Cloud Community and using bardapi==0.1.11

**Comment by Saugatkafley** [comment] 2023-06-12 06:52
@thispath98  Can anything be done? Like i dont understand whats the problem. It could be of some internal proxies used by streamlit ? 

If someone understand please mention what could have gone wrong ?

**Comment by Saugatkafley** [comment] 2023-06-12 06:54
Do you know any other platforms like streamlit ?

**Comment by polishdataengineer** [comment] 2023-06-23 07:41
There is a Google site request check and limit.
![image](https://github.com/dsdanielpark/Bard-API/assets/69598075/060304d6-7a26-407b-b5c6-2bf41b6c7a35)

I think the problem will occur more often :( - I've received the same errors in IDE + via Bard over my web browser using VPN of course - because in my country the Bard service is unavailable.
<img width="615" alt="image" src="https://github.com/dsdanielpark/Bard-API/assets/69598075/9644da1f-e9fb-43fb-bfbf-5c650ce1c2ed">

At the moment, I do not have a solution for these limitations and I think we will have to wait for an official Bard API

**Comment by HemanthBunny** [comment] 2023-06-26 17:37
I had the following code snippet in my code : 

def generate_response(prompt):
    bard = Bard(token=token)
    response = bard.get_answer(prompt)['content']
    return response

And I was getting this error. Initially it all went good without any such errors, but now IDK  why is it happening. Tried clearing cookies and replacing the _Secure-1PSID token value, but nothing worked. Is that because I exceeded my maximum tries? If that's the case, Bard is working fine for me on the other hand. Help me out please...
 
TypeError: 'NoneType' object is not subscriptable
File "C:\Users\Hemanth\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 119, in get_answer
    "content": parsed_answer[0][0]

**Comment by jjsong23** [comment] 2023-06-26 17:44
> I had the following code snippet in my code :
> 
> def generate_response(prompt): bard = Bard(token=token) response = bard.get_answer(prompt)['content'] return response
> 
> And I was getting this error. Initially it all went good without any such errors, but now IDK why is it happening. Tried clearing cookies and replacing the _Secure-1PSID token value, but nothing worked. Is that because I exceeded my maximum tries? If that's the case, Bard is working fine for me on the other hand. Help me out please...
> 
> TypeError: 'NoneType' object is not subscriptable File "C:\Users\Hemanth\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 119, in get_answer "content": parsed_answer[0][0]

I just got the exact same error. I checked Bard's activity and it seems like the questions are still being prompted.

**Comment by HemanthBunny** [comment] 2023-06-26 17:49
Is that solved?

**Comment by Duttabhi** [comment] 2023-08-27 15:53
I am also getting the same error. After sending few requests it starts throwing the error

[/usr/local/lib/python3.10/dist-packages/bardapi/core.py](https://localhost:8080/#) in _get_snim0e(self)
    126         snim0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text)
    127         if not snim0e:
--> 128             raise Exception(
    129                 "SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'."
    130             )

Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

**Comment by ZOC-cyber** [comment] 2023-10-05 02:09
I did succeed in logging on Bard once, but later on I could never log on, though I updated and renewed cooies in Chrome and snippets. The errors are:Traceback (most recent call last):
  File "path/file.py", line 403, in <module>
    bard = Bard(token=token, session=session)
  File "E:\anaconda3\Lib\site-packages\bardapi\core.py", line 78, in __init__
    self.SNlM0e = self._get_snim0e()
  File "E:\anaconda3\Lib\site-packages\bardapi\core.py", line 142, in _get_snim0e
    raise Exception(
Exception: __Secure-1PSID value must end with a single dot. Enter correct __Secure-1PSID value.
I tried many times. The problem can not be solved. What shall I do? THANKS!

My Snippets are:# # import os
# import bardapi
# import requests
# from bardapi.constants import SESSION_HEADERS
# from bardapi import Bard

# # print(bardapi.__version__)##0.1.38

# # os.environ['HTTP_PROXY'] = 'http://IP:PORT' 
# # os.environ['HTTPS_PROXY'] = 'https://IP:PORT'
# # os.environ['_BARD_API_KEY'] = 'XXX.'

# token = "XXXX."

# session = requests.Session()
# session.headers = SESSION_HEADERS
# session.cookies.set("__Secure-1PSID", token)
# session.cookies.set("__Secure-1PSIDTS", "XXX")
# session.cookies.set("__Secure-1PSIDCC", "XXX")


# bard = Bard(token=token, session=session)

# res = bard.get_answer("Do you like cookies?")
# print(res)

Can anyone help me? Many thanks!

**Comment by sr3shreya** [comment] 2023-12-15 08:02
I am getting SSL certificate error:
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bard.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

my code:
from bardapi import Bard
__BARD_API_KEY ="xxxxxxx."
bard = Bard(__BARD_API_KEY)
answer = bard.get_answer("what is the date today?")

**Comment by ublzesc** [comment] 2023-12-21 18:11
> **Occurs when response is not possible.**
> 
> 1. First, check if the Google Bard is officially in service. You need to access **https://bard.google.com/** with your account and check if the result for the prompt is returned normally. If it is not an officially **serviced area**, the package will not work.
>    
>    * Visit https://bard.google.com/ and check if you are in the right state to talk to the bard. You need to press Try Bard on https://bard.google.com/
>    * Bard's current official service area can be viewed at: https://support.google.com/bard/answer/13575153?hl=en
> 2. Second, check if you copied the value of `__Secure-1PSID` correctly. Also, restart your browser and try again. It may be a non-response error due to an invalid cookie. `__Secure-1PSID` values ​​end with single a dot.
>    
>    * ex) os.environ['__BARD_API_KEY'] = VwhV4124qhvFp3nOm_sSsLszdr2u_DWm8otZBt3hPR9fud2BePGTk2jQmGmfcbKb_vyr3IjJFKEP.
> 3. In case of response error due to server delay and use in proxy server, use `timeout` or `proxies` argument after **version 0.1.3.**
> 
> 
> I've also found that the same error sometimes occurs during normal processes. Please give it some time or try resetting your cookie values manually.
> 
> If the same error is repeated even after checking all of the above, please tell me **your Python environment, country, and region.**

Hey my __Secure-1PSID doesn't end with dot, why do you assert that? I had to do a workaround with BardCookies.

**Comment by dsdanielpark** [comment] 2024-03-05 08:22
[NOTICE] Please, go to Gemini-API https://github.com/dsdanielpark/Gemini-API



<div align="right">
  <a href="https://pypi.org/project/python-gemini-api/">
    <img alt="PyPI" src="https://img.shields.io/pypi/v/python-gemini-api?color=pink">
  </a>
</div>

# <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg" width="35px" alt="Gemini Icon" /> Google - Gemini API 


A *unofficial* Python wrapper, [python-gemini-api](https://pypi.org/project/python-gemini-api/), operates through reverse-engineering, utilizing cookie values to interact with [Google Gemini](https://gemini.google.com) for users struggling with frequent authentication problems or unable to authenticate via [Google Authentication](https://developers.google.com/identity/protocols/oauth2?hl=en).

Collaborated competently with [Antonio Cheong](https://github.com/acheong08).


## What is [Gemini](https://deepmind.google/technologies/gemini/#introduction)?

[[Paper](https://arxiv.org/abs/2312.11805)] [[Official Website](https://deepmind.google/technologies/gemini/#introduction)] [[Official API](https://aistudio.google.com/)] [[API Documents](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini)]

Gemini is a family of generative AI models developed by Google DeepMind that is designed for multimodal use cases. The Gemini API gives you access to the Gemini Pro and Gemini Pro Vision models. In February 2024, Google's **Bard** service was changed to **Gemini**.

  - [Installation](#installation)
  - [Authentication](#authentication)
  - [Usage](#usage)
    - [Initialization](#initialization)
    - [Text generation](#text-generation)
    - [Image generation](#image-generation)
    - [Generate content with image](#generate-content-with-image)
    - [Text To Speech(TTS) from Gemini](#text-to-speechtts-from-gemini)
  - [Further](#further)
    - [Behind a proxy](#behind-a-proxy)
    - [Use rotating proxies](#use-rotating-proxies)
    - [Reusable session object](#reusable-session-object)
  - [More features](#more-features)



<br>



## Installation
```bash
pip install python-gemini-api
```
```bash
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```
For the updated version, use as follows:
```
pip install -q -U python-gemini-api
```

**Closed by dsdanielpark** 2024-03-05 08:22 UTC
