### ISSUE TITLE
Long answers getting cut off

### ISSUE THREAD

**Issue by danschnettler** [dsdanielpark/Bard-API#68] opened 2023-06-20 21:18 UTC
Is it possible to make sure Bard's responses don't get cut off even if they are very long answers?

**Comment by dsdanielpark** [comment] 2023-06-21 04:42
Please give me some questions that can get long answers cut-offed.

**Comment by danschnettler** [comment] 2023-06-21 15:29
just for example "give me a 1000 word blog post about top gaming monitors 2023 in html" The answer will get cut off mid html

**Comment by dsdanielpark** [comment] 2023-06-21 16:25
I have confirmed that it is not possible to implement this on the Google Bard website. This is because the bard API is a simplified package that provides more streamlined request and response handling compared to what is available on the Google Bard website. Additionally, other large language models also commonly impose limitations on the size of output tokens.

Therefore, since this issue is not related to the bard-api Python package, I am unable to resolve it.

I will close this issue.

**Closed by dsdanielpark** 2023-06-21 16:25 UTC
