### ISSUE TITLE
'coroutine' object is not subscriptable

### ISSUE THREAD

**Issue by Piyushoberoy** [dsdanielpark/Bard-API#195] opened 2023-09-30 19:21 UTC
💚💜 Thank you for interest. ❤️💛

**To Reproduce**
- [X] I have read [README.md](https://github.com/dsdanielpark/Bard-API). Please read me.
- [X] I have searched for existing issues.
- [X] I installed the appropriate version and confirmed that the previous version was properly removed upon reinstallation. 
- [X] I also checked the environment (not only on a single local machine but also on Google Colab, and different Google accounts, and tried resetting cookies, etc.)

**Describe the bug**
In the code given below, it is showing that "coroutine" cannot be subscribable. Kindly resolve this issue since I want to get the text output of my input. Kindly tell me any other approach to do this thing

**Version**
OS: Windows 11
Python: 3.8.10

**Code**
```python
from bardapi import Bard

token = tk #ignore token part its already set of my bard account __Secure-1PSID
bard = Bard(token=token)
bard.get_answer("hello")['content']
```

**Error**
```
TypeError                                 Traceback (most recent call last)
[k:\PROJECTS\gpt.ipynb](file:///K:/PROJECTS/gpt.ipynb) Cell 18 line 1
----> [1](vscode-notebook-cell:/k%3A/PROJECTS/gpt.ipynb#X35sZmlsZQ%3D%3D?line=0) bard.get_answer("hello")['content']

TypeError: 'coroutine' object is not subscriptable
```

**Comment by dsdanielpark** [comment] 2023-10-02 12:33
The error message "TypeError: 'coroutine' object is not subscriptable" typically occurs when you try to access or subscript a coroutine object in Python, which is not allowed. Coroutines are used for asynchronous programming and require special handling.

To resolve this error, you should await the coroutine and then access its result. Here's an example of how to do it:

```python
import asyncio

async def my_coroutine():
    # Some asynchronous operations
    await asyncio.sleep(1)
    return [1, 2, 3]

async def main():
    result = await my_coroutine()  # Await the coroutine to get the result
    print(result[0])  # Now you can subscript the result

asyncio.run(main())
```

In this example, we define an asynchronous coroutine `my_coroutine` that sleeps for a second and returns a list. We then use `await` to execute the coroutine and get the result, allowing us to subscript the list without any errors.

I will check async bard, soon.

**Comment by dsdanielpark** [comment] 2023-10-02 13:01
However, the code you provided does not include asynchronous handling, so the mentioned error continues to persist. Could you please confirm whether this is a reproducible issue and whether it has occurred elsewhere??

**Comment by Piyushoberoy** [comment] 2023-10-03 17:33
Well, thanks, for your quick reply I tried the same method but it didn't work, but when I tried again today without handling the "coroutine" it worked fine maybe there was some backend issue(bug) or bard restrictions that automatically resolved.

**Comment by dsdanielpark** [comment] 2023-10-04 14:48
It seems to be a similar issue to #193. While the actual speed is the same, you might consider adding elements that make the user feel less frustrated. For example, you can start by gradually showing text using a simple algorithm or rule for the initial part before Bard's response is completed and an object is assigned, then display it right below. Apart from that, there's no other way to achieve this through the current OpenAI API for text generation models. This is because the API is highly limited in its functionality. Additionally, Bard is not a specialized text generation model; it's a multi-modality generative AI with various experimental elements, so while providing services in that manner might be possible, I believe there's a high chance it won't be supported.

**Closed by dsdanielpark** 2023-10-04 14:48 UTC
