### ISSUE TITLE
SNlM0e value not found in response

### ISSUE THREAD

**Issue by zicas2000** [dsdanielpark/Bard-API#18] opened 2023-05-18 08:56 UTC
I have tried to interpret core python code to C# with the help of Chatgpt as I'm just a newbie in this field , It generated the full code to be applicable for integration with Unity. but I have got the error "SNlM0e value not found in response".
I don't know what is the issue, it might be related to my location ?
and here is the code

```c#
using UnityEngine;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Net.Http;
using System;
using UnityEngine.Networking;
using System.Linq;

public class Bard
{
    private Dictionary<string, string> proxies;
    private int timeout;
    private Dictionary<string, string> headers;
    private int _reqid;
    private string conversation_id;
    private string response_id;
    private string choice_id;
    private HttpClient httpClient;
    private string SNlM0e;

    public Bard(int timeout = 6, Dictionary<string, string> proxies = null)
    {
        this.proxies = proxies;
        this.timeout = timeout;
        this.headers = new Dictionary<string, string>
        {
            { "Host", "bard.google.com" },
            { "X-Same-Domain", "1" },
            { "User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" },
            { "Content-Type", "application/x-www-form-urlencoded;charset=UTF-8" },
            { "Origin", "https://bard.google.com" },
            { "Referer", "https://bard.google.com/" }
        };
        this._reqid = int.Parse(string.Join("", UnityEngine.Random.Range(0, 10), UnityEngine.Random.Range(0, 10), UnityEngine.Random.Range(0, 10), UnityEngine.Random.Range(0, 10)));
        this.conversation_id = "";
        this.response_id = "";
        this.choice_id = "";
        this.httpClient = new HttpClient();
        this.httpClient.DefaultRequestHeaders.Clear();
        this.httpClient.DefaultRequestHeaders.Host = "bard.google.com";
        this.httpClient.DefaultRequestHeaders.Add("X-Same-Domain", "1");
        this.httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36");
        this.httpClient.DefaultRequestHeaders.Accept.ParseAdd("application/x-www-form-urlencoded;charset=UTF-8");
        this.httpClient.DefaultRequestHeaders.Referrer = new Uri("https://bard.google.com/");

       // this.httpClient.DefaultRequestHeaders.Add("Cookie", "__Secure-1PSID=" + Environment.GetEnvironmentVariable("_BARD_API_KEY"));

        this.httpClient.DefaultRequestHeaders.Add("Cookie", "__Secure-1PSID=Wgi8wUobo4-2WaJ29Y45F_fGhfjh4GjtcOMkBamz5_dJ4gogfwcocBxvS2PRxuEiJsS4ww.");

        this.SNlM0e = this._get_snim0e();
    }

    private string _get_snim0e()
    {
        var requestUri = "https://bard.google.com/";
        var response = httpClient.GetAsync(requestUri).Result;

        if (!response.IsSuccessStatusCode)
        {
            throw new Exception($"Response Status: {response.StatusCode}");
        }

        var responseContent = response.Content.ReadAsStringAsync().Result;
        Debug.Log("responseContent" + responseContent);
        var match = Regex.Match(responseContent, "SNlM0e\":\"(.*?)\"");
        if (!match.Success)
        {
            throw new Exception("SNlM0e value not found in response.");
        }

        return match.Groups[1].Value;
    }

    public Dictionary<string, object> GetAnswer(string inputText)
    {
        var url = "https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate";
        var paramsDict = new Dictionary<string, string>
    {
        { "bl", "boq_assistant-bard-web-server_20230419.00_p1" },
        { "_reqid", this._reqid.ToString() },
        { "rt", "c" }
    };

        var inputTextStruct = new List<object[]>
    {
        new object[] { inputText },
        null,
        new object[] { this.conversation_id, this.response_id, this.choice_id }
    };

        var dataDict = new Dictionary<string, string>
    {
        { "f.req", JsonUtility.ToJson(new object[] { null, JsonUtility.ToJson(inputTextStruct) }) },
        { "at", this.SNlM0e }
    };

        var formData = new WWWForm();
        foreach (var kvp in dataDict)
        {
            formData.AddField(kvp.Key, kvp.Value);
        }

        var request = UnityWebRequest.Post(url, formData);
        request.SetRequestHeader("Host", "bard.google.com");
        request.SetRequestHeader("X-Same-Domain", "1");
        request.SetRequestHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36");
        request.SetRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
        request.SetRequestHeader("Origin", "https://bard.google.com");
        request.SetRequestHeader("Referer", "https://bard.google.com/");

        var response = request.SendWebRequest();

        while (!response.isDone) { }

        if (request.result != UnityWebRequest.Result.Success)
        {
            return new Dictionary<string, object> { { "content", $"Response Error: {request.error}." } };
        }

        var responseContent = request.downloadHandler.text;
        var responseLines = responseContent.Split('\n');
        var respDict = JsonUtility.FromJson<DictionaryResponse>(responseLines[3]);
        var respJson = JsonUtility.ToJson(new DictionaryResponse { Content = respDict.Content });
        var parsedAnswer = JsonUtility.FromJson<DictionaryAnswer>(respJson);
        var bardAnswer = new Dictionary<string, object>
    {
        { "content", parsedAnswer.Content[0][0] },
        { "conversation_id", parsedAnswer.Content[1][0] },
        { "response_id", parsedAnswer.Content[1][1] },
        { "factualityQueries", parsedAnswer.Content[3] },
        { "textQuery", parsedAnswer.Content[2][0] != null ? parsedAnswer.Content[2][0] : "" },
        { "choices", parsedAnswer.Content[4].Select(item => new Dictionary<string, object> { { "id", item[0] }, { "content", item[1] } }).ToList() }
    };

        this.conversation_id = (string)bardAnswer["conversation_id"];
        this.response_id = (string)bardAnswer["response_id"];
        choice_id = ((List<Dictionary<string, object>>)bardAnswer["choices"])[0]["id"].ToString(); this._reqid += 100000;

        return bardAnswer;
    }

    [System.Serializable]
    public class DictionaryResponse
    {
        public object[][] Content;
    }

    [System.Serializable]
    public class DictionaryAnswer
    {
        public object[][][] Content;
    }

}

```

**Comment by dsdanielpark** [comment] 2023-05-18 09:12
Try setting the `__Secure-1PSID` value as a variable. `__Secure-1PSID`  ends with sing dot.

**Comment by zicas2000** [comment] 2023-05-18 09:46
I did that but still receive the same error
"SNlM0e value not found in response" 
as I defined in the exception.

**Comment by dsdanielpark** [comment] 2023-05-18 10:06
See #1 and check first whether you can receive normal results with the Python package. If you still can't solve it, ask Chat GPT for another translation or request optimization.

**Comment by zicas2000** [comment] 2023-05-18 11:44
I tried another code version and I received the "SNlM0e" value but I'm not sure about it's format, when I log it in the console I got this 
SNlM0e":"AFuTz6u398zPNr1aA3ILCQhl2MEr:1684404414628".
but eventually I receive "Response Error: HTTP/1.1 400 Bad Request"

**Comment by dsdanielpark** [comment] 2023-05-18 12:17
Before using the following code, please make sure to declare the __Secure-1PSID value, which ends with a single dot, in the _BARD_API_KEY. Then you can proceed to use the following code.

in lunux
```
export_BARD_API_KEY="xxxxxxxxxxxxxxxxxxx."
```

in windows
```
set _BARD_API_KEY="xxxxxxxxxxxxxxxxxxx."
```


C# Code
```C#
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace BardNamespace
{
    public class Bard
    {
        private const string BARD_HOST = "bard.google.com";
        private const string BARD_URL = "https://bard.google.com/";
        private const string STREAM_GENERATE_URL = "https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate";

        private static readonly Dictionary<string, string> HEADERS = new Dictionary<string, string>()
        {
            { "Host", BARD_HOST },
            { "X-Same-Domain", "1" },
            { "User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" },
            { "Content-Type", "application/x-www-form-urlencoded;charset=UTF-8" },
            { "Origin", BARD_URL },
            { "Referer", BARD_URL }
        };

        private readonly string token;
        private readonly int timeout;
        private readonly Dictionary<string, string> proxies;
        private int reqId;
        private string conversationId;
        private string responseId;
        private string choiceId;
        private readonly HttpClient client;

        public Bard(string token = null, int timeout = 20, Dictionary<string, string> proxies = null, HttpClient session = null)
        {
            this.token = token ?? Environment.GetEnvironmentVariable("_BARD_API_KEY");
            this.timeout = timeout;
            this.proxies = proxies;
            this.reqId = new Random().Next(1000, 9999);
            this.conversationId = "";
            this.responseId = "";
            this.choiceId = "";
            this.client = session ?? new HttpClient();
            this.client.DefaultRequestHeaders.Clear();
            foreach (var header in HEADERS)
            {
                this.client.DefaultRequestHeaders.Add(header.Key, header.Value);
            }
            this.client.DefaultRequestHeaders.Add("Cookie", $"__Secure-1PSID={this.token}");
            this.SNlM0e = GetSnim0eAsync().GetAwaiter().GetResult();
        }

        private async Task<string> GetSnim0eAsync()
        {
            if (string.IsNullOrEmpty(token) || token[token.Length - 1] != '.')
            {
                throw new Exception("__Secure-1PSID value must end with a single dot. Enter correct __Secure-1PSID value.");
            }

            HttpResponseMessage response = await client.GetAsync(BARD_URL);
            response.EnsureSuccessStatusCode();
            string responseBody = await response.Content.ReadAsStringAsync();
            Match match = Regex.Match(responseBody, @"SNlM0e\":\"(.*?)\"");
            if (!match.Success)
            {
                throw new Exception("SNlM0e value not found in response. Check __Secure-1PSID value.");
            }
            return match.Groups[1].Value;
        }

        public async Task<Dictionary<string, object>> GetAnswer(string inputText)
        {
            var parameters = new Dictionary<string, string>()
            {
                { "bl", "boq_assistant-bard-web-server_20230419.00_p1" },
                { "_reqid", reqId.ToString() },
                { "rt", "c" }
            };
            var inputTextStruct = new List<object[]>
            {
                new object[]
                {
                    new List<string> { inputText },
                    null,
                    new List<string> { conversationId, responseId, choiceId }
                }
            };
            var data = new Dictionary<string, string>()
            {
                { "f.req", $"[null, {JsonSerializer.Serialize(inputTextStruct)}]" },
                { "at", SNlM0e }
            };
            var response = await client.PostAsync(STREAM_GENERATE_URL + GetQueryString(parameters), new FormUrlEncodedContent(data));
            response.EnsureSuccessStatusCode();
            var responseContent = await response.Content.ReadAsStringAsync();
            var responseArray = JArray.Parse(responseContent);
            var parsedAnswer = (JArray)responseArray[0][2];
            if (parsedAnswer == null)
            {
                return new Dictionary<string, object> { { "content", $"Response Error: {responseContent}." } };
            }

            var choices = new List<Dictionary<string, object>>();
            foreach (var choice in parsedAnswer[4])
            {
                choices.Add(new Dictionary<string, object> { { "id", choice[0] }, { "content", choice[1] } });
            }

            var bardAnswer = new Dictionary<string, object>
            {
                { "content", parsedAnswer[0][0] },
                { "conversation_id", parsedAnswer[1][0] },
                { "response_id", parsedAnswer[1][1] },
                { "factualityQueries", parsedAnswer[3] },
                { "textQuery", parsedAnswer[2][0]?.ToString() ?? "" },
                { "choices", choices }
            };

            conversationId = (string)bardAnswer["conversation_id"];
            responseId = (string)bardAnswer["response_id"];
            choiceId = (string)choices[0]["id"];
            reqId += 100000;

            return bardAnswer;
        }

        private string GetQueryString(Dictionary<string, string> parameters)
        {
            var stringBuilder = new StringBuilder("?");
            foreach (var parameter in parameters)
            {
                stringBuilder.Append($"{Uri.EscapeDataString(parameter.Key)}={Uri.EscapeDataString(parameter.Value)}&");
            }
            return stringBuilder.ToString().TrimEnd('&');
        }
    }
}

```

**Comment by dsdanielpark** [comment] 2023-05-18 13:48
I am closing this issue as it is a duplicate of #1 and not an error in the python package.

**Closed by dsdanielpark** 2023-05-18 13:48 UTC
