### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JVTEAM** [dsdanielpark/Bard-API#81] opened 2023-06-28 12:46 UTC
This was working great for awhile, but it's suddenly not working.  Appears to be an issue in the bardapi/core.py file

Traceback (most recent call last):
  File "chatbard.py", line 23, in <module>
    response = Bard().get_answer(input_text)
  File "/usr/local/lib/python3.6/dist-packages/bardapi/core.py", line 113, in get_answer
    resp_dict = json.loads(resp.content.splitlines()[3])[0][2]
IndexError: list index out of range

from bardapi import Bard
import os
import socket
import signal

os.environ['_BARD_API_KEY']="MYKEY."

s = socket.socket()
port = xxxxx
s.bind(('', port))
s.listen(5)
c, addr = s.accept()

def process_text(text):
    split_text = text.split(".")
    
    if len(split_text) > 1 and split_text[0].lower().startswith("sure"):
        split_text = split_text[1:]
    
    processed_text = ".".join(split_text)
    return processed_text

print("Socket Up and running with a connection from",addr)

while True:
    rcvdData = c.recv(1024).decode()
    print("S:",rcvdData)
    input_text = rcvdData
    answer = Bard().get_answer(input_text)['content']
    response = process_text(answer)
    print("S: " + response)
    sendData = (response)
    c.send(str(sendData).encode())
    if(sendData == "Bye" or sendData == "bye"):
        break
c.close()

**Comment by dsdanielpark** [comment] 2023-06-28 15:25
We are aware of the issue and it is slightly delayed due to other project deadlines. The goal is to resolve this issue in version 0.1.20 within 48 hours. If there is an update, we will provide the update by modifying the comments of this issue.

**Comment by dsdanielpark** [comment] 2023-06-28 20:54
This issue overlaps with #78 and #80, and it can be resolved by using `pip install bardapi>=0.1.18`. The current latest version is `0.1.20`, which includes some updates to the features of ChatBard.

The mentioned issue will be resolved if you use version 0.1.18 or above. Additionally, by utilizing [reusable sessions](https://github.com/dsdanielpark/Bard-API#reusable-session-object), you will be able to use your code more efficiently.

**Comment by JVTEAM** [comment] 2023-06-28 23:58
> This issue overlaps with #78 and #80, and it can be resolved by using `pip install bardapi>=0.1.18`. The current latest version is `0.1.20`, which includes some updates to the features of ChatBard.
> 
> The mentioned issue will be resolved if you use version 0.1.18 or above. Additionally, by utilizing [reusable sessions](https://github.com/dsdanielpark/Bard-API#reusable-session-object), you will be able to use your code more efficiently.

This was actually one of the first things I did as I saw it on the issues page...however I get no feedback from the command (no error or progress) and there is no effect to the issue.

**Comment by dsdanielpark** [comment] 2023-06-29 02:09
Where can I find 'chatbard.py' in your error message?

**Comment by JVTEAM** [comment] 2023-06-29 12:15
> Where can I find `chatbard.py` in your error message?

The code I posted in the OP is chatbard.py

It's part of a couple different scripts working together.  A facial recognition camera looks for a face.  If it sees one it sends a webhook to an flask server that connects to this script.  The response is then sent back to the flask server that sends it to google natural language processor to play the text as speech.

**Comment by Nipun1212** [comment] 2023-07-05 08:47
I uninstalled and re installed bardapi but still getting this error
any fixes?
File ~/Desktop/Projects/AI_Playlist_Maker/venv/lib/python3.10/site-packages/bardapi/core.py:113, in Bard.get_answer(self, input_text)
    102 data = {
    103     "f.req": json.dumps([None, json.dumps(input_text_struct)]),
    104     "at": self.SNlM0e,
    105 }
    106 resp = self.session.post(
    107     "https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate",
    108     params=params,
   (...)
    111     proxies=self.proxies,
    112 )
--> 113 resp_dict = json.loads(resp.content.splitlines()[3])[0][2]
    115 if not resp_dict:
    116     return {"content": f"Response Error: {resp.content}."}

IndexError: list index out of range

**Comment by dsdanielpark** [comment] 2023-07-05 09:56
Please modify line 113 as follows and try using a separate instance of the
Bard class. While your error is not ordinary, it may not be incorporated
into the entire project code. However, if this error occurs repeatedly for
other users, updates can be made. Additionally, there is a possibility that
it may not work properly depending on the environment, so I recommend
resetting the virtual environment.

resp_dict = None
resp_lines = resp.content.splitlines()
if len(resp_lines) > 3:
    resp_json = json.loads(resp_lines[3])
    if len(resp_json) > 0:
        resp_dict = resp_json[0][2]
else:
    raise "Abnormal reponse."


2023년 7월 5일 (수) 오후 5:48, Nipun Bhatia ***@***.***>님이 작성:

**Comment by dsdanielpark** [comment] 2023-07-05 09:57
Please modify line 113 as follows and try using a separate instance of the Bard class. While your error is not ordinary, it may not be incorporated into the entire project code. However, if this error occurs repeatedly for other users, updates can be made. Additionally, there is a possibility that it may not work properly depending on the environment, so I recommend resetting the virtual environment.

```python
resp_dict = None
resp_lines = resp.content.splitlines()
if len(resp_lines) > 3:
    resp_json = json.loads(resp_lines[3])
    if len(resp_json) > 0:
        resp_dict = resp_json[0][2]
else:
    raise "Abnormal reponse."


2023년 7월 5일 (수) 오후 5:48, Nipun Bhatia <notifications@github.com>님이 작성:
I uninstalled and re installed bardapi but still getting this error
any fixes?
File ~/Desktop/Projects/AI_Playlist_Maker/venv/lib/python3.10/site-packages/bardapi/core.py:113, in Bard.get_answer(self, input_text)
102 data = {
103 "f.req": json.dumps([None, json.dumps(input_text_struct)]),
104 "at": self.SNlM0e,
105 }
106 resp = [self.session.post](http://self.session.post/)(
107 "https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate",
108 params=params,
(...)
111 proxies=self.proxies,
112 )
--> 113 resp_dict = json.loads(resp.content.splitlines()[3])[0][2]
115 if not resp_dict:
116 return {"content": f"Response Error: {resp.content}."}

IndexError: list index out of range

```

**Comment by Nipun1212** [comment] 2023-07-05 10:08
yup I tried running on my base python and it worked, I think might be the venv issue, I'll try resetting it.
Thanks a lot.

**Comment by TakuyaSekiyama** [comment] 2023-07-06 23:49
I got also encountering the same Error.
I have tried versions 0.1.22 to 0.1.24, but they all return [IndexError: list index out of range].
(I installed all ver. by [pip install bardapi=0.1.xx]. I also uninstalled the previous version before installing each ver.)
The same code was responding correctly until 3 days ago.
I use Google Colablatory, is this also an effect of the environment?

**Comment by zxzhijia** [comment] 2023-07-09 05:14
I got the same list index out of range error too.

**Comment by dsdanielpark** [comment] 2023-07-09 15:40
The following two errors can stem from various causes. Additionally, this may result in a temporary ban due to bard's internal interface policies and restrictions, network conditions, account issues, improper bard invocations, or excessive calls.

If you are a developer testing certain functionalities temporarily and have made all the necessary calls correctly, it might be a transient issue. However, if that is not the case, the resolution may be difficult.

As emphasized in the `readme.md` or elsewhere, this package is intended for developers to implement, test, and mock certain functionalities before the official release of bard's API. It is not meant for actual production use, and we recommend using it responsibly.

Please note that the errors encountered may not be due to issues within this package but could be caused by the virtual environment, network setup, bardapi version, or improper removal of the existing bardapi.

Due to the wide range of possible causes, we apologize for not being able to provide a specific solution. Thank you.


<br>


### Possible causes for the two errors can vary, and they may not be attributed to package errors.

```
IndexError: list index out of range
```

<br>

```
'Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n54\n[["di",89],["af.httprm",89,"7855032709640118140",8]]\n25\n[["e",4,null,null,129]]\n'. 

Temporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.'
```

**Comment by abalgir** [comment] 2023-07-11 17:15
Hi, I  am testing a small app using bardapi. I updated to  bardapi-0.1.24 from bardapi-0.1.18 and I had a very simple input_text ="What can you tell me about International Business Machines Corporation financials ". 
My code is , using python 3.11: 
```
from bardapi import Bard
response = (Bard ().get_answer ( input_text ) [ 'content' ])

```
And I started getting the error while calling Bard ().get_answer : list index out of range.
It worked well until last week on bardapi-0.1.18, and now started to give this error.
If anyone found a workaround solution, I would appreciate the help.
GR

**Comment by dsdanielpark** [comment] 2023-07-24 09:15
Even though the PSID cookie value may appear unchanged, it will be different if you reset the cookies or restart the browser. Since frequent changes in the PSID value are reported, we recommend refreshing or verifying the cookie value to address this error.

**Comment by abalgir** [comment] 2023-08-09 14:53
I created a virtual environment with Ubuntu. Run streamlit with a reverse Nginx proxy and I’ve been able to connect. I suppose streamlit HUB blocks some type of calls , since even Google news api did not work on Streamlit HUB , but same code on Ubuntu works. Best GRSent from my iPhoneOn Aug 9, 2023, at 09:31, Raijin-3 ***@***.***> wrote:﻿

Try updating the PSID, that worked for me.

This worked for me well.

**Closed** 2024-01-18 15:53 UTC
