### ISSUE TITLE
Response error

### ISSUE THREAD

**Issue by tic-top** [dsdanielpark/Bard-API#75] opened 2023-06-24 18:58 UTC
I try the colab demo. However, there is a reponse error.
`Response Error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n56\n[["di",201],["af.httprm",201,"6329365286172527438",0]]\n25\n[["e",4,null,null,131]]\n'.`
![image](https://github.com/dsdanielpark/Bard-API/assets/78676563/6b911131-4966-4316-9f7b-4036808a11ec)

**Comment by dsdanielpark** [comment] 2023-06-25 00:43
I have confirmed once again that it is functioning properly. Please check for various possibilities such as network environment, availability of the bard experimental version, normal functioning of the region, and whether a proxy server is being used. 

Since you can find more detailed information in issue #1, I will close this issue. 

Furthermore, regarding the response error, it may not be due to cookie value errors, but could be an error based on network or other server conditions, even when following the normal procedures.

**Closed by dsdanielpark** 2023-06-25 00:43 UTC
