### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by siam38** [dsdanielpark/Bard-API#146] opened 2023-07-29 15:53 UTC
"Response Error: b')]}\\'\\n\\n39\\n[[\"wrb.fr\",null,null,null,null,[13]]]\\n58\\n[[\"di\",5022],[\"af.httprm\",5022,\"1384621268006285802\",6]]\\n25\\n[[\"e\",4,null,null,134]]\\n'. \nUnable to get response.\nPlease double-check the cookie values and verify your network environment or google account.

**Comment by dsdanielpark** [comment] 2023-07-30 16:34
There could be various reasons for the recurring issue. It is not a package error, and regular QA and CI for functionality are being conducted.

This error is due to abnormal responses from Google's internal interfaces, such as regional/account/rate limiting policies. Therefore, it cannot be resolved within this package, and you may need to check the root cause in different environments.

You can try logging out or renewing cookies, bypassing other servers, or checking on platforms like Colab.

**Closed by dsdanielpark** 2023-07-30 16:34 UTC
