### ISSUE TITLE
Bard do not have any ask_about_image feature

### ISSUE THREAD

**Issue by Rahul-singh7906** [dsdanielpark/Bard-API#141] opened 2023-07-27 11:22 UTC
AttributeError: 'Bard' object has no attribute 'ask_about_image'

<img width="532" alt="issue" src="https://github.com/dsdanielpark/Bard-API/assets/91553428/c188c5b5-6989-46e7-bcd7-facd2bddb4e7">

tried various functions like: analyze_image etc. but none is working to provide image input.

**Comment by yihong0618** [comment] 2023-07-27 11:39
pip install -U bardapi

**Comment by Rahul-singh7906** [comment] 2023-07-28 03:46
> 

no, I am getting this error even after installing all the dependencies.

**Comment by dsdanielpark** [comment] 2023-07-30 17:01
This error is also not related to the bardapi package.

As mentioned in the readme, this feature is inherently unavailable for some accounts and regions. Therefore, even in Colab or other environments, please first verify if you can ask and receive valid questions about images at https://bard.google.com/.

For example, the ask_about_image method worked fine when using the cookie value from a European account in Google Colab, but it was not usable when logging in from Korea and refreshing the Google account's cookie value.

Thus, this method may be unavailable due to various limitations imposed by Google, regardless of region or account, as explicitly stated in the [readme.md](https://github.com/dsdanielpark/Bard-API#bard-ask_about_image-method).

**Comment by dsdanielpark** [comment] 2023-07-30 17:02
This error is not caused by any issue in the bardapi code. It is a normal occurrence due to numerous cases where it is unavailable based on Google's internal API policies. As a result, we cannot provide support for this. Therefore, we are closing this issue.

**Closed by dsdanielpark** 2023-07-30 17:02 UTC

**Comment by Rahul-singh7906** [comment] 2023-07-30 17:48
thanks for the reply, but I think I am able to use the image input feature
in my bard.google.com account but I am unable to use that in api call via
cookies.

**Comment by dsdanielpark** [comment] 2023-07-30 18:01
Can you show a different error message? The "method does not exist" error is likely due to not installing the version properly.

If it's an issue with the Bard API package, I'm curious about the current error you are facing for more detailed debugging.
Also, I would like to know if the calls to get_answer are working properly.

**Comment by armintum** [comment] 2023-07-31 21:22
I am using version 0.1.29 and I am also getting "AttributeError: 'BardAsync' object has no attribute 'ask_about_image'". However, I only get this error when I use `bard.ask_about_image` with BardAsync. Non-async works perfectly fine.

**Comment by dsdanielpark** [comment] 2023-08-01 01:23
[armintum](https://github.com/armintum) Please use `0.1.30`. we add ask_about_image method in BardAsync class.

**Comment by Rahul-singh7906** [comment] 2023-08-01 17:31
> [armintum](https://github.com/armintum) Please use `0.1.30`. we add ask_about_image method in BardAsync class. We fixed that issue.
> 
> ```
> pip install bardapi==0.1.30
> 
> # or
> 
> pip install -U bardapi==0.1.30
> ```

yes, it's working now. thanks a lot!
