### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xupeng19881010** [dsdanielpark/Bard-API#233] opened 2023-11-26 08:01 UTC
stderr:   File "/usr/local/lib/python3.10/site-packages/bardapi/core.py", line 332, in get_answer
stderr:     resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
stderr: IndexError: list index out of range

**Comment by BriskPlayz** [comment] 2023-11-29 10:47
I am also getting the same error "list index out of range". Please someone tell the solution. I have tried Updating bardapi from version 0.1.34 -> 0.1.38
Still getting same error.

**Comment by dsdanielpark** [comment] 2023-11-30 18:49
Is the error still recurring? There seems to be no problem with the code, and it is working normally. Which countries are you two in, and are you using a proxy?

**Comment by dsdanielpark** [comment] 2023-12-01 15:08
This error is not reproducible, and you can debug in detail through the guidance of the following FAQ. Also, please try calling the method in a different way.

If the error persists, please reopen this issue with a proper issue template (including OS and code).

Since this error is non-reproducible and may not be a package issue, and is likely to be a problem that cannot be resolved at the package level, I am closing this issue.

**Closed by dsdanielpark** 2023-12-01 15:08 UTC
