### ISSUE TITLE
Is Bad API currently available? 

### ISSUE THREAD

**Issue by mistercoderrre** [dsdanielpark/Bard-API#257] opened 2024-01-05 11:33 UTC
Is the Bard API currently available? 
There are currently two problems I have. 
I am currently using all three keys because I know that it needs to have three keys for it to work well. 

1 problem: First, the Bad API can be initialized only the first two or three times, and after the second or third times, the key does not match and cannot be created. 

2 problem : Even if it is initialized and created once or twice, most of the time, no response is received even when requested. At this time, when you go to the Bard website, there are questions, but there are no answers because it seems to be an external access. At this time, when you ask a question on the website Bard, an answer is generated well. 

If anyone is using it well, can I get a sample code?  thanks for everyone

**Comment by SuSl1KK** [comment] 2024-01-05 15:43
1: The Secure-1PSIDCC and Secure-1PSIDTS updating every 20 minutes, so you have to update them manually or automatically using browser_cookie3 lib. Also, when using automatic method, AI will forget everything in the past conversation, because API will create a new, empty one when new session cookies will be set.

2: can you post small snippet of the code you're using to get response? Maybe you got problems here, because for me all is working absolutely fine

**Comment by dsdanielpark** [comment] 2024-01-06 03:50
The package has been confirmed to be working properly, so I'm closing this issue. I recommend referring to the readme, existing issues, and the FAQ page for solutions. Thank you.

**Closed by dsdanielpark** 2024-01-06 03:50 UTC
