### ISSUE TITLE
Response Error: b')]}\\'\\n\\n38\\n[[\"wrb.fr\",null,null,null,null,[8]]]\\n54\\n[[\"di\",59],[\"af.httprm\",59,\"4239016509367430469\",0]]\\n25\\n[[\"e\",4,null,null,129]]\\n'. \nTemporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment.

### ISSUE THREAD

**Issue by leimeng86** [dsdanielpark/Bard-API#128] opened 2023-07-20 02:25 UTC
Hi, there:

I encountered the response error using `bardapi` to `ask_about_image`:

`"Response Error: b')]}\\'\\n\\n38\\n[[\"wrb.fr\",null,null,null,null,[8]]]\\n54\\n[[\"di\",59],[\"af.httprm\",59,\"4239016509367430469\",0]]\\n25\\n[[\"e\",4,null,null,129]]\\n'. \nTemporarily unavailable due to traffic or an error in cookie values. Please double-check the cookie values and verify your network environment."`

Then I tried again the Bard UI, and got this warning message.

Is anyone seeing this warning message? And what can we do about it?

**Comment by sachnun** [comment] 2023-07-20 05:42
upgrade package to the dev version, it's been fixed #125

**Comment by yihong0618** [comment] 2023-07-21 08:14
> Use dev version until update pypi version.
> 
> ```
> $ pip install git+https://github.com/dsdanielpark/Bard-API.git
> ```

pip install -U git+https://github.com/dsdanielpark/Bard-API.git

**Comment by dsdanielpark** [comment] 2023-07-22 02:46
Successfully upade at 23.07.22 

Release note: https://github.com/dsdanielpark/Bard-API/releases/edit/0.1.28

### 0.1.28
```
$ pip install bardapi==0.1.28
```
*It may not work as it is only available for certain accounts, regions, and other restrictions.*

- Contributor: [senseibence](https://github.com/senseibence), [yihong0618](https://github.com/yihong0618)
- PR Index: #121 #125 #130
- Build Git Hash: 1284b5c6ac6afc7efccff632f1f6c72f1d348b9c
  - Forced header to "start" to allow multiple image uploads to URL #121
  - API changed related to [Ask About Image method](https://github.com/dsdanielpark/Bard-API#bard-ask_about_image-method) #125
  - Delete error message that can confuse users. #130

**Comment by dsdanielpark** [comment] 2023-07-30 17:16
There could be various reasons for the recurring issue. 

It is not a Bard-API package code error, I have conducted regular QA and CI for functionality.

This error is due to abnormal responses from Google's internal interfaces, such as regional/account/rate limiting policies. Therefore, it cannot be resolved within this package, and you may need to check the root cause in different environments.

You can try logging out or renewing cookies, bypassing other servers, or checking on platforms like Colab.


1. Update BardAPI package (ensure the previous version is deleted).
2. Refresh cookie values (log out, completely close the browser, then reopen and log in to use updated cookies).
3. There might be rate limiting, so wait a few hours before trying again.
Most users reported that the issue was resolved after following these steps.

Please share your user experience related to this error in issue #128. Thank you.

**Comment by abalgir** [comment] 2023-07-31 17:59
Hello,
It seems I have the same issue but in a different environment.
I have a simple code that works perfectly on my local machine but generates an error when deployed on Streamlit. I am using the bardapi from [GitHub - dsdanielpark/Bard-API: The unofficial python package that returns response of Google Bard through cookie value.](https://github.com/dsdanielpark/Bard-API) and using the latest version.

```
import streamlit as st
from dotenv.main import load_dotenv
import os
load_dotenv()
st.title("BardAPI for Python")

_BARD_API_KEY=os.environ['_BARD_API_KEY']
#import os
from bardapi import Bard

with st.container () :

    with st.spinner ( 'Wait till Bard gets the answers...' ) :
        input_text = "What is the largest state in the USA?"

        try :
            bard = Bard ( token = _BARD_API_KEY, timeout = 20 )
            response = (bard.get_answer ( input_text ) [ 'content' ])
            st.write ( response )
        except :
            st.error ( 'Please check if you have set the Cookie ' )
```
on the local machine, I get:

BardAPI for Python

> The largest state in the USA is Alaska. It has a total area of 586,412 square miles, which is more than two and a half times the size of Texas, the second largest state. Alaska is also the least densely populated state in the USA, with a population of only about 733,000 people.
> 
> Here is a list of the 10 largest states in the USA, ranked by total area:
> 
> Alaska (586,412 square miles)
> Texas (268,596 square miles)
> California (163,695 square miles)
> Montana (147,046 square miles)
> New Mexico (121,590 square miles)
> Arizona (113,990 square miles)
> Nevada (110,572 square miles)
> Colorado (104,094 square miles)
> Oregon (98,379 square miles)
> Wyoming (97,813 square miles)
> I hope this helps! Let me know if you have any other questions.

on Streamlit Hub I get:

> BardAPI for Python
> 
> Response Error: b’)]}‘\n\n38\n[[“[wrb.fr](http://wrb.fr/)”,null,null,null,null,[9]]]\n56\n[[“di”,163],[“af.httprm”,163,“7269046257447756350”,0]]\n25\n[[“e”,4,null,null,131]]\n’. Unable to get response. Please double-check the cookie values and verify your network environment or google account.
> 

I am using the same cookie; nothing changed.
Any help is appreciated.
Thank you

**Comment by vsynytsia** [comment] 2023-08-03 16:57
> 

hello, have you managed to resolve the problem?

**Comment by vsynytsia** [comment] 2023-08-03 16:58
> Hello, It seems I have the same issue but in a different environment. I have a simple code that works perfectly on my local machine but generates an error when deployed on Streamlit. I am using the bardapi from [GitHub - dsdanielpark/Bard-API: The unofficial python package that returns response of Google Bard through cookie value.](https://github.com/dsdanielpark/Bard-API) and using the latest version. in requirements.txt I have bardapi==0.1.29
> 
> ```
> import streamlit as st
> from dotenv.main import load_dotenv
> import os
> load_dotenv()
> st.title("BardAPI for Python")
> 
> _BARD_API_KEY=os.environ['_BARD_API_KEY']
> #import os
> from bardapi import Bard
> 
> with st.container () :
> 
>     with st.spinner ( 'Wait till Bard gets the answers...' ) :
>         input_text = "What is the largest state in the USA?"
> 
>         try :
>             bard = Bard ( token = _BARD_API_KEY, timeout = 20 )
>             response = (bard.get_answer ( input_text ) [ 'content' ])
>             st.write ( response )
>         except :
>             st.error ( 'Please check if you have set the Cookie ' )
> ```
> 
> on the local machine, I get:
> 
> BardAPI for Python
> 
> > The largest state in the USA is Alaska. It has a total area of 586,412 square miles, which is more than two and a half times the size of Texas, the second largest state. Alaska is also the least densely populated state in the USA, with a population of only about 733,000 people.
> > Here is a list of the 10 largest states in the USA, ranked by total area:
> > Alaska (586,412 square miles)
> > Texas (268,596 square miles)
> > California (163,695 square miles)
> > Montana (147,046 square miles)
> > New Mexico (121,590 square miles)
> > Arizona (113,990 square miles)
> > Nevada (110,572 square miles)
> > Colorado (104,094 square miles)
> > Oregon (98,379 square miles)
> > Wyoming (97,813 square miles)
> > I hope this helps! Let me know if you have any other questions.
> 
> on Streamlit Hub I get:
> 
> > BardAPI for Python
> > Response Error: b’)]}‘\n\n38\n[[“[wrb.fr](http://wrb.fr/)”,null,null,null,null,[9]]]\n56\n[[“di”,163],[“af.httprm”,163,“7269046257447756350”,0]]\n25\n[[“e”,4,null,null,131]]\n’. Unable to get response. Please double-check the cookie values and verify your network environment or google account.
> 
> I am using the same cookie; nothing changed. Any help is appreciated. Thank you

hi, have you managed to resolve the problem?

**Comment by abalgir** [comment] 2023-08-03 18:06
No , I could not find a solution. Even after following the suggestions: logging out, clearing all cookies, logging in again, using the new value. It does not work.

**Comment by dsdanielpark** [comment] 2023-08-09 02:10
> No , I could not find a solution. Even after following the suggestions: logging out, clearing all cookies, logging in again, using the new value. It does not work.

This issue is also related to Google, where for reasons like region, account lock, public IP blocking, or response limits, responses are not being received. 

The role of the Bard API package is to send requests and receive responses, which is working perfectly. 

Therefore, there's nothing we can do to resolve it. If this is not a temporary issue, it would be difficult to use.

**Comment by wajihmsedi** [comment] 2023-08-18 10:08
I keep getting the same error even by changing account IP etc. 
Does it help to join the makersuite ?

**Comment by Waterkin** [comment] 2023-10-12 02:28
Reopen the chrome solves the problem.

**Comment by Gaoc3** [comment] 2023-10-21 03:44
I have the same problem, when I want to extract the code and convert it to a link, it tells me: 

`{'content': 'Response Error: b\')]}\\\'\\n\\n39\\n[["wrb.fr",null,null,null,null,[13]]]\\n54\\n[["di",82],["af.httprm",82,"6645275065783071985",2]]\\n25\\n[["e",4,null,null,130]]\\n\'. \nUnable to get response.\nPlease double-check the cookie values and verify your network environment or google account.'}`

**Closed** 2024-03-05 08:21 UTC
Labels: good first issue
